[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["bankruptcy/*", "pyproject.toml"]

[deploy]
startCommand = "uv run -m bankruptcy"
restartPolicyType = "NEVER"
cronSchedule = "*/5 * * * *"
