[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["closeout/*", "pyproject.toml"]

[deploy]
startCommand = "uv run -m closeout"
restartPolicyType = "NEVER"
cronSchedule = "5 * * * *"
