[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["liquidation/*", "pyproject.toml"]

[deploy]
startCommand = "uv run -m liquidation"
restartPolicyType = "NEVER"
cronSchedule = "* * * * *"
